apiVersion: v1
kind: Service
metadata:
  name: lmsbackend
  namespace: {{ .Values.namespace }}
  labels:
    app: lmsbackend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: lmsbackend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP