apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmsbackend
  namespace: {{ .Values.namespace }}
  labels:
    app: lmsbackend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: lmsbackend
  template:
    metadata:
      labels:
        app: lmsbackend
    spec:
      containers:
        - name: lmsbackend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: PORT
              value: "{{ .Values.backend.port }}"

            - name: CLIENT_URL
              value: "{{ .Values.app.clientUrl }}"

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret }}
                  key: DATABASE_URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret }}
                  key: JWT_SECRET