apiVersion: v1
kind: Service
metadata:
  name: lmspostgres
  namespace: lms
spec:
  type: ClusterIP
  selector:
    app: lmspostgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort:  {{ .Values.postgres.port }}