apiVersion: batch/v1
kind: Job
metadata:
  name: lms-prisma-db-push
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: prisma
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              set -e

              echo "Running Prisma db push..."
              npx prisma db push
              echo "Database setup completed."
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret }}
                  key: DATABASE_URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret }}
                  key: JWT_SECRET
  backoffLimit: 3