namespace: lms

backend:
  image:
    repository: xpocky/lmsbackend
    tag: latest
    pullPolicy: Always
  port: 5000
  replicas: 1

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

secrets:
  existingSecret: lms-secrets

app:
  clientUrl: "http://localhost:5173"
